# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Image.create([image_id: 'age00', keywords: '古代', path: 'age00.png'])
Image.create([image_id: 'age01', keywords: '中世', path: 'age01.png'])
Image.create([image_id: 'age02', keywords: 'モダン', path: 'age02.png'])
Image.create([image_id: 'animal00', keywords: '絶滅', path: 'animal00.png'])
Image.create([image_id: 'animal01', keywords: '野生', path: 'animal01.png'])
Image.create([image_id: 'animal02', keywords: '象', path: 'animal02.png'])
Image.create([image_id: 'animal03', keywords: '鳥', path: 'animal03.png'])
Image.create([image_id: 'animal04', keywords: 'パンダ', path: 'animal04.png'])
Image.create([image_id: 'animal05', keywords: '珍獣', path: 'animal05.png'])
Image.create([image_id: 'animal06', keywords: 'サファリ', path: 'animal06.png'])
Image.create([image_id: 'animal07', keywords: '魚', path: 'animal07.png'])
Image.create([image_id: 'feel00', keywords: '興奮', path: 'feel00.png'])
Image.create([image_id: 'feel01', keywords: '気まま', path: 'feel01.png'])
Image.create([image_id: 'feel02', keywords: '魅惑', path: 'feel02.png'])
Image.create([image_id: 'feel03', keywords: '癒やし', path: 'feel03.png'])
Image.create([image_id: 'feel04', keywords: '楽園', path: 'feel04.png'])
Image.create([image_id: 'feel05', keywords: '放浪', path: 'feel05.png'])
Image.create([image_id: 'feel06', keywords: '学ぶ', path: 'feel06.png'])
Image.create([image_id: 'food00', keywords: '飲み放題', path: 'food00.png'])
Image.create([image_id: 'food01', keywords: '旬', path: 'food01.png'])
Image.create([image_id: 'food02', keywords: 'ワイン', path: 'food02.png'])
Image.create([image_id: 'food03', keywords: 'ビール', path: 'food03.png'])
Image.create([image_id: 'food04', keywords: 'グルメ', path: 'food04.png'])
Image.create([image_id: 'food05', keywords: '食べ放題', path: 'food05.png'])
Image.create([image_id: 'nature00', keywords: '山脈', path: 'nature00.png'])
Image.create([image_id: 'nature01', keywords: '海', path: 'nature01.png'])
Image.create([image_id: 'nature02', keywords: '空', path: 'nature02.png'])
Image.create([image_id: 'nature03', keywords: 'オーロラ', path: 'nature03.png'])
Image.create([image_id: 'nature04', keywords: '雪', path: 'nature04.png'])
Image.create([image_id: 'nature05', keywords: '氷', path: 'nature05.png'])
Image.create([image_id: 'nature06', keywords: '星', path: 'nature06.png'])
Image.create([image_id: 'nature07', keywords: '宇宙', path: 'nature07.png'])
Image.create([image_id: 'nature08', keywords: '熱帯', path: 'nature08.png'])
Image.create([image_id: 'person00', keywords: '子連れ', path: 'person00.png'])
Image.create([image_id: 'person01', keywords: 'ひとり', path: 'person01.png'])
Image.create([image_id: 'person02', keywords: 'ハネムーン', path: 'person02.png'])
Image.create([image_id: 'person03', keywords: '女子', path: 'person03.png'])
Image.create([image_id: 'person04', keywords: 'ホームステイ', path: 'person04.png'])
Image.create([image_id: 'person05', keywords: '添乗員', path: 'person05.png'])
Image.create([image_id: 'scene00', keywords: '絶景', path: 'scene00.png'])
Image.create([image_id: 'scene01', keywords: '歴史', path: 'scene01.png'])
Image.create([image_id: 'scene02', keywords: '田舎', path: 'scene02.png'])
Image.create([image_id: 'scene03', keywords: '都会', path: 'scene03.png'])
Image.create([image_id: 'scene04', keywords: '世界一周', path: 'scene04.png'])
Image.create([image_id: 'scene05', keywords: '旧市街', path: 'scene05.png'])
Image.create([image_id: 'scene06', keywords: 'シルクロード', path: 'scene06.png'])
Image.create([image_id: 'sports00', keywords: '観戦', path: 'sports00.png'])
Image.create([image_id: 'sports01', keywords: 'ゴルフ', path: 'sports01.png'])
Image.create([image_id: 'sports02', keywords: 'スノボー', path: 'sports02.png'])
Image.create([image_id: 'sports03', keywords: 'ダイビング', path: 'sports03.png'])
Image.create([image_id: 'sports04', keywords: 'スカイダイビング', path: 'sports04.png'])
Image.create([image_id: 'sports05', keywords: '登山', path: 'sports05.png'])
Image.create([image_id: 'sports06', keywords: 'テニス', path: 'sports06.png'])
Image.create([image_id: 'spot00', keywords: '美術館', path: 'spot00.png'])
Image.create([image_id: 'spot01', keywords: 'カジノ', path: 'spot01.png'])
Image.create([image_id: 'spot02', keywords: 'リゾート', path: 'spot02.png'])
Image.create([image_id: 'spot03', keywords: '祭り', path: 'spot03.png'])
Image.create([image_id: 'spot04', keywords: 'ロケ地', path: 'spot04.png'])
Image.create([image_id: 'spot05', keywords: '温泉', path: 'spot05.png'])
Image.create([image_id: 'spot06', keywords: '冒険', path: 'spot06.png'])
Image.create([image_id: 'spot07', keywords: '戦地', path: 'spot07.png'])
Image.create([image_id: 'spot08', keywords: '少数民族', path: 'spot08.png'])
Image.create([image_id: 'spot09', keywords: 'ミュージカル', path: 'spot09.png'])
Image.create([image_id: 'spot10', keywords: 'エステ', path: 'spot10.png'])
Image.create([image_id: 'spot11', keywords: '卒業', path: 'spot11.png'])
Image.create([image_id: 'trans00', keywords: '鉄道', path: 'trans00.png'])
Image.create([image_id: 'trans01', keywords: 'バス', path: 'trans01.png'])
Image.create([image_id: 'trans02', keywords: '船', path: 'trans02.png'])
Image.create([image_id: 'trans03', keywords: '気球', path: 'trans03.png'])
Image.create([image_id: 'trans04', keywords: 'ボート', path: 'trans04.png'])

